In [50]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
%matplotlib inline

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
p_id = test_data['PassengerId']
data = pd.concat([train_data, test_data])

In [51]:
data.drop('PassengerId', axis=1, inplace=True)
survived = data['Survived'].dropna()
data['Survived'].fillna(-1, inplace=True)

In [52]:
def enc(dataframe, name):
    dataframe = pd.concat([dataframe, pd.get_dummies(dataframe[name])
                           .rename(columns=lambda x: name + str(x))], axis=1)
    return dataframe.drop(name, axis=1)

In [53]:
dummies_Cabin = pd.get_dummies(data_train['Cabin'], prefix= 'Cabin')

dummies_Embarked = pd.get_dummies(data_train['Embarked'], prefix= 'Embarked')

dummies_Sex = pd.get_dummies(data_train['Sex'], prefix= 'Sex')

dummies_Pclass = pd.get_dummies(data_train['Pclass'], prefix= 'Pclass')

df = pd.concat([data_train, dummies_Cabin, dummies_Embarked, dummies_Sex, dummies_Pclass], axis=1)
df.drop(['Pclass', 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], axis=1, inplace=True)
df

,PassengerId,Survived,Age,SibSp,Parch,Fare,Cabin_No,Cabin_Yes,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male,Pclass_1,Pclass_2,Pclass_3
0,1,0,22.000000,1,0,7.2500,1,0,0,0,1,0,1,0,0,1
1,2,1,38.000000,1,0,71.2833,0,1,1,0,0,1,0,1,0,0
2,3,1,26.000000,0,0,7.9250,1,0,0,0,1,1,0,0,0,1
3,4,1,35.000000,1,0,53.1000,0,1,0,0,1,1,0,1,0,0
4,5,0,35.000000,0,0,8.0500,1,0,0,0,1,0,1,0,0,1
5,6,0,23.838953,0,0,8.4583,1,0,0,1,0,0,1,0,0,1
6,7,0,54.000000,0,0,51.8625,0,1,0,0,1,0,1,1,0,0
7,8,0,2.000000,3,1,21.0750,1,0,0,0,1,0,1,0,0,1
8,9,1,27.000000,0,2,11.1333,1,0,0,0,1,1,0,0,0,1
9,10,1,14.000000,1,0,30.0708,1,0,1,0,0,1,0,0,1,0
10,11,1,4.000000,1,1,16.7000,0,1,0,0,1,1,0,0,0,1
11,12,1,58.000000,0,0,26.5500,0,1,0,0,1,1,0,1,0,0
12,13,0,20.000000,0,0,8.0500,1,0,0,0,1,0,1,0,0,1
13,14,0,39.000000,1,5,31.2750,1,0,0,0,1,0,1,0,0,1
14,15,0,14.000000,0,0,7.8542,1,0,0,0,1,1,0,0,0,1
15,16,1,55.000000,0,0,16.0000,1,0,0,0,1,1,0,0,1,0
16,17,0,2.000000,4,1,29.1250,1,0,0,1,0,0,1,0,0,1
17,18,1,32.066493,0,0,13.0000,1,0,0,0,1,0,1,0,1,0
18,19,0,31.000000,1,0,18.0000,1,0,0,0,1,1,0,0,0,1
19,20,1,29.518205,0,0,7.2250,1,0,1,0,0,1,0,0,0,1
20,21,0,35.000000,0,0,26.0000,1,0,0,0,1,0,1,0,1,0
21,22,1,34.000000,0,0,13.0000,0,1,0,0,1,0,1,0,1,0
22,23,1,15.000000,0,0,8.0292,1,0,0,1,0,1,0,0,0,1
23,24,1,28.000000,0,0,35.5000,0,1,0,0,1,0,1,1,0,0
24,25,0,8.000000,3,1,21.0750,1,0,0,0,1,1,0,0,0,1
25,26,1,38.000000,1,5,31.3875,1,0,0,0,1,1,0,0,0,1
26,27,0,29.518205,0,0,7.2250,1,0,1,0,0,0,1,0,0,1
27,28,0,19.000000,3,2,263.0000,0,1,0,0,1,0,1,1,0,0
28,29,1,22.380113,0,0,7.8792,1,0,0,1,0,1,0,0,0,1
29,30,0,27.947206,0,0,7.8958,1,0,0,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,21.000000,1,0,11.5000,1,0,0,0,1,0,1,0,1,0
862,863,1,48.000000,0,0,25.9292,0,1,0,0,1,1,0,1,0,0
863,864,0,10.869867,8,2,69.5500,1,0,0,0,1,1,0,0,0,1
864,865,0,24.000000,0,0,13.0000,1,0,0,0,1,0,1,0,1,0
865,866,1,42.000000,0,0,13.0000,1,0,0,0,1,1,0,0,1,0
866,867,1,27.000000,1,0,13.8583,1,0,1,0,0,1,0,0,1,0
867,868,0,31.000000,0,0,50.4958,0,1,0,0,1,0,1,1,0,0
868,869,0,25.977889,0,0,9.5000,1,0,0,0,1,0,1,0,0,1
869,870,1,4.000000,1,1,11.1333,1,0,0,0,1,0,1,0,0,1
870,871,0,26.000000,0,0,7.8958,1,0,0,0,1,0,1,0,0,1
871,872,1,47.000000,1,1,52.5542,0,1,0,0,1,1,0,1,0,0
872,873,0,33.000000,0,0,5.0000,0,1,0,0,1,0,1,1,0,0
873,874,0,47.000000,0,0,9.0000,1,0,0,0,1,0,1,0,0,1
874,875,1,28.000000,1,0,24.0000,1,0,1,0,0,1,0,0,1,0
875,876,1,15.000000,0,0,7.2250,1,0,1,0,0,1,0,0,0,1
876,877,0,20.000000,0,0,9.8458,1,0,0,0,1,0,1,0,0,1
877,878,0,19.000000,0,0,7.8958,1,0,0,0,1,0,1,0,0,1
878,879,0,27.947206,0,0,7.8958,1,0,0,0,1,0,1,0,0,1
879,880,1,56.000000,0,1,83.1583,0,1,1,0,0,1,0,1,0,0
880,881,1,25.000000,0,1,26.0000,1,0,0,0,1,1,0,0,1,0
881,882,0,33.000000,0,0,7.8958,1,0,0,0,1,0,1,0,0,1
882,883,0,22.000000,0,0,10.5167,1,0,0,0,1,1,0,0,0,1
883,884,0,28.000000,0,0,10.5000,1,0,0,0,1,0,1,0,1,0
884,885,0,25.000000,0,0,7.0500,1,0,0,0,1,0,1,0,0,1
885,886,0,39.000000,0,5,29.1250,1,0,0,1,0,1,0,0,0,1
886,887,0,27.000000,0,0,13.0000,1,0,0,0,1,0,1,0,1,0
887,888,1,19.000000,0,0,30.0000,0,1,0,0,1,1,0,1,0,0
888,889,0,16.193950,1,2,23.4500,1,0,0,0,1,1,0,0,0,1
889,890,1,26.000000,0,0,30.0000,0,1,1,0,0,0,1,1,0,0
890,891,0,32.000000,0,0,7.7500,1,0,0,1,0,0,1,0,0,1

In [54]:
processed_data = preprocess_data(data)

training_data = processed_data[data['Survived'] != -1]
testing_data = processed_data[data['Survived'] == -1]

training_data.drop('Survived', axis=1, inplace=True)
testing_data.drop('Survived', axis=1, inplace=True)

X_train, X_test, y_train, y_test = train_test_split(training_data, survived, test_size=0.20, random_state=42)

/Library/Python/2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Library/Python/2.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [55]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

models = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    DecisionTreeClassifier(max_depth=10),
    RandomForestClassifier(n_estimators=100),
    MLPClassifier(),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()
]

for model in models:
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    print(score)

0.754189944134
0.782122905028
0.754189944134
0.77094972067
0.798882681564
0.810055865922
0.776536312849
0.743016759777
0.413407821229